// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGVYnrX9ziIbmvfUdJk8nmt5_dH9FCM0',
    appId: '1:1040793169187:web:f9a80e0bd47b250f4db096',
    messagingSenderId: '1040793169187',
    projectId: 'trashify-db',
    authDomain: 'trashify-db.firebaseapp.com',
    storageBucket: 'trashify-db.firebasestorage.app',
    measurementId: 'G-2E7VTMVNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIavpnYx7LDkIh1ZkWM5FoRntPSFz6TI0',
    appId: '1:1040793169187:android:a85353cd9b5c89614db096',
    messagingSenderId: '1040793169187',
    projectId: 'trashify-db',
    storageBucket: 'trashify-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyJQONIPq6x6_-_B3fNRC9FnOGIA6Vbc',
    appId: '1:1040793169187:ios:c1dff1ee7a119e004db096',
    messagingSenderId: '1040793169187',
    projectId: 'trashify-db',
    storageBucket: 'trashify-db.firebasestorage.app',
    iosBundleId: 'com.example.trashbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyJQONIPq6x6_-_B3fNRC9FnOGIA6Vbc',
    appId: '1:1040793169187:ios:c1dff1ee7a119e004db096',
    messagingSenderId: '1040793169187',
    projectId: 'trashify-db',
    storageBucket: 'trashify-db.firebasestorage.app',
    iosBundleId: 'com.example.trashbin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZGVYnrX9ziIbmvfUdJk8nmt5_dH9FCM0',
    appId: '1:1040793169187:web:16475352709cc5c64db096',
    messagingSenderId: '1040793169187',
    projectId: 'trashify-db',
    authDomain: 'trashify-db.firebaseapp.com',
    storageBucket: 'trashify-db.firebasestorage.app',
    measurementId: 'G-HGLMEXZEMM',
  );
}
